# Generated by Django 5.0.4 on 2024-04-25 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_employee_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['active'], 'verbose_name': 'Рейтинг ПД', 'verbose_name_plural': 'Рейтинг ПД'},
        ),
        migrations.AddField(
            model_name='employee',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
