# Generated by Django 5.0.4 on 2024-04-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_employee_options_employee_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='time_created',
        ),
    ]
