# Generated by Django 5.0.4 on 2024-04-25 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_employee_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
