# Generated by Django 5.0.4 on 2024-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_employee_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.CharField(default='', max_length=255),
        ),
    ]
