# Generated by Django 5.0.4 on 2024-04-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_employee_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role_in_project',
            field=models.CharField(default='', max_length=255),
        ),
    ]
