# Generated by Django 5.0.4 on 2024-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_employee_role_in_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Оценка проектов',
                'verbose_name_plural': 'Оценка проектов',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
    ]
