# Generated by Django 5.0.4 on 2024-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_score_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='fio',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
