# Generated by Django 5.0.4 on 2024-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_score_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='init',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='fio',
            field=models.CharField(default='', max_length=200),
        ),
    ]
