# Generated by Django 5.0.4 on 2024-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_employee_personal_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='project_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='type_project',
            field=models.CharField(default='', max_length=200),
        ),
    ]
